### ISSUE TITLE
Comply with Policy for Source Code Management

### ISSUE THREAD

**Issue by achaikou** [equinor/vds-slice#217]
(SCM policy to be find under internal link)

**Comment by AdilKhurshid** [comment]
In order to comply our repository with the SCM, we must include the following elements in our repository.

- [ ] Add a CONTRIBUTING.md file to the root of your repository or include a Contributing paragraph in your README.md.
- [ ] Add an overview of workflow and specific expectations for pull requests like (style guides, commit messages, tests, code formatting etc)
- [ ] Add Security.md file which contains security guidelines, reporting security issues or vulnerabilities associated with this repo.
