### ISSUE TITLE
swag 1.8.8 breaks Docker container

### ISSUE THREAD

**Issue by ajaust** [equinor/vds-slice#59]
With the latest release ([v1.8.8](https://github.com/swaggo/swag/releases/tag/v1.8.8)) of [swag](https://github.com/swaggo/swag) the Docker container fails to build with the following error:

```
~/go/bin/swag init -g cmd/query/main.go --md docs
2022/11/28 14:27:44 Generate swagger docs....
2022/11/28 14:27:44 Generate general API Info, search dir:./
2022/11/28 14:27:44 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /Users/aej/projects/vds-slice
2022/11/28 14:27:44 ParseComment error in file /Users/aej/projects/vds-slice/api/query.go :cannot find type definition: vds.Metadata
```

I tested `swag@v1.8.7` for which the build of the documentation also shows a warning (same as for `swag@v1.8.8`), but is still built without error:

```
2022/11/28 14:40:15 Generate swagger docs....
2022/11/28 14:40:15 Generate general API Info, search dir:./
2022/11/28 14:40:15 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /Users/aej/projects/vds-slice
2022/11/28 14:40:15 Generating vds.Metadata
2022/11/28 14:40:15 Generating vds.BoundingBox
2022/11/28 14:40:15 Generating vds.Axis
2022/11/28 14:40:15 Generating api.ErrorResponse
2022/11/28 14:40:15 Generating api.MetadataRequest
2022/11/28 14:40:15 Generating api.BaseRequest
2022/11/28 14:40:15 Generating vds.SliceMetadata
2022/11/28 14:40:15 Generating api.SliceRequest
2022/11/28 14:40:15 Generating vds.FenceMetadata
2022/11/28 14:40:15 Generating api.FenceRequest
2022/11/28 14:40:15 create docs.go at  docs/docs.go
2022/11/28 14:40:15 create swagger.json at  docs/swagger.json
2022/11/28 14:40:15 create swagger.yaml at  docs/swagger.yaml
``` 

Should we pin the version in the Dockerfile to `v1.8.7` or should we rather fix the what creates the issue with swagger `v1.8.8`? I am unsure if this error is an issue with swag or with our package. I did not find any issue pointing to this problem in the swag repository. I can also reproduce the error locally on MacOS.

**Comment by ErlendHaa** [comment]
This can be solved by referring to the struct by it's "Swagger name", (e.g. [in the case of Metadata](https://github.com/equinor/vds-slice/blob/5dec18ff75ad15d5c9be4c4e5643f24616d81c86/internal/vds/vds.go#L95)). I.e substituting `vds.Metadata` for `Metadata` [here](https://github.com/equinor/vds-slice/blob/5dec18ff75ad15d5c9be4c4e5643f24616d81c86/api/query.go#L181) and in other places.

Assuming this was an intentional change I think we should fix it on our side

**Comment by ajaust** [comment]
Changing the names as proposed fixes it for me. I will create a PR.

**Comment by achaikou** [comment]
> This can be solved by referring to the struct by it's "Swagger name",

Out of interest, where did you get that from? 

As far as I see, that's a breaking change, which is highly unlikely to appear between 1.8.7 and 1.8.8. Which most likely indicates it was not intentional or that it was a bug in the first place which got fixed.
OR we were using something incorrectly. I see that there is a "parseInternal" command line option that we never even used and everything somehow worked without it. Though it is unclear when it is supposed to be used. Maybe if something refers to type internal packages are searched automatically.

And as far as I see, docks still refer to packaged names (not internal)

```
@Success      200  {object}  model.Account
@Failure      400  {object}  httputil.HTTPError
```

Anyway, something is weird, but I don't know what.

To our problem: it might make more sense to pin the version instead of having to upgrade local environment whenever something weird happens. And judging by issues, this is not uncommon. It might be that even this one wasn't intentional.

**Comment by ajaust** [comment]
I think you are right that removing the prefix `vds` actually breaks the documentation for `swag@v1.8.7`. So I agree that this might not be the correct fix and/or a bug in swag.

**Comment by yngve793** [comment]
Adding a go file to the root of the project only containing "package main" resolved the problem for unknown reason.
Updating swag to latests implies that a series of other go packages must be updated. Implications of this is not clear.
